# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("1") do |config|
  config.vm.boot_mode = :gui
end
Vagrant.configure(2) do |config|

  config.vm.box = "minimal/xenial64"

  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.synced_folder "../", "/project"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "samplerdev"

    #Enable audio (different drivers are required depending on host OS)
    if RUBY_PLATFORM =~ /darwin/
        vb.customize ["modifyvm", :id, '--audio', 'coreaudio', '--audiocontroller', 'hda']
    elsif RUBY_PLATFORM =~ /mingw|mswin|bccwin|cygwin|emx/
        vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'ac97']
    elsif RUBY_PLATFORM =~ /linux/
        vb.customize ["modifyvm", :id, "--audio", "pulse", "--audiocontroller", "hda"]
    end

    #Enable video acceleration and increase the VRAM
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
